### ISSUE TITLE
Having an error with Automated Text UI Testing

### ISSUE THREAD

**Issue by TheodoreKooo** [nus-cs2103-AY2324S2/forum#70] opened 2024-01-24 11:08 UTC
Hello, i am trying out the Automated Text UI Testing. I am on macOS and am getting the error runtest.sh: line 27: dos2unix: command not found.

Also, how should i present my input and outputs? e.g. should my input be "bye\n" instead of bye? 

Thanks

**Comment by E0735389** [comment] 2024-01-24 11:08
Duplicate of #69

**Comment by E0735389** [comment] 2024-01-24 11:09
Refer to the linked issue for how to install the program on Mac.

**Comment by bgopi23** [comment] 2024-01-24 12:12
brew install dos2unix

i used System.out.print(...) instead of System.out.println(...) so i dont get an extra empty line when my chatbot sends the terminating message (bye)

**Comment by damithc** [comment] 2024-01-25 03:31
@TheodoreKooo Is this issue resolved now?

**Comment by neyapraveen** [comment] 2024-01-29 18:32
Hi @TheodoreKooo, if the issue is resolved do remember to close this issue :)

**Closed** 2024-02-11 04:36 UTC
Labels: suitableForPeerHelp, type-HelpRequest :sos:
