### ISSUE TITLE
Smoke Test Help for Windows and Linux

### ISSUE THREAD

**Issue by tayziyi** [nus-cs2103-AY2324S2/forum#439] opened 2024-02-27 16:06 UTC
Hey! Looking for people to help with smoke testing:
Please download from [here](https://github.com/tayziyi/ip/releases/tag/A-Release2)

Thanks in advance!

**Comment by simkianseng** [comment] 2024-02-27 18:39
LGTM :smile:.

Perhaps can add this line of code, `dialog.setMinHeight(Region.USE_PREF_SIZE);` to the `DialogBox` constructor? This fixes the issue of the content of the label not being fully shown as it seems that overflow content appears to get cut off as shown below.

<img width="368" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/67402819/bd2fa8c7-5efa-4dd5-88a5-80716fdd0dc1">

**Comment by ghost** [comment] 2024-02-28 10:45
Tested on Ubuntu 22.04.03 LTS, through VMWare Workstation 17 Player

Test Environment:
OS: Ubuntu 22.04.03 LTS
JDK: openJDK 11.0.20.1

Command executed
```
java -jar SecretaryW.jar
```

Terminal Output
```
Feb 28, 2024 6:39:34 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @1ee178c8'
```

Files created on program execution, relative to 
```
./secretary.txt
```

Screenshot of program
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/110957723/10728bff-2406-4ee6-a336-f74b4ce23a72)

Basic functionality works as intended

**Comment by lhy-hoyin** [comment] 2024-02-28 17:52
Hi @tayziyi , I'm a senior from a previous batch and is helping you to smoke test using Linux (Ubuntu 22.04.4).
For some context:, running `java --version`
```shell
openjdk 11.0.22 2024-01-16
OpenJDK Runtime Environment (build 11.0.22+7-post-Ubuntu-0ubuntu222.04.1)
OpenJDK 64-Bit Server VM (build 11.0.22+7-post-Ubuntu-0ubuntu222.04.1, mixed mode, sharing)
```

Running `java -jar SecretaryW.jar` gives:
```shell
Feb 29, 2024 1:16:03 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @602ffa63'
Error in glXCreateNewContext, remote GLX is likely disabled
```

Testing of basic functionality seems to go well.

---
However, I spotted some minor bugs.

|Bug|To replicate|Expected|Actual|
|---|---|---|---|
|typo for required date format|`deadline something /by today`|dd/mm/yyyy|d/mm/yyyy|
|generic error message regarding date|`deadline milestone one /by 1/23/2024`|Some error message about invalid date|Error saying wrong date format|
|Unhandled invalid index for mark|`mark 0` or `mark -1`|Some kind of message telling me its invalid|Nothing happening on the UI; Back-end throwing `IndexOutOfBoundsException`|
|Unhandled invalid argument for delete|`delete one`|Some kind of message telling me its invalid|Nothing happening on the UI; Back-end throwing `NumberFormatException`|

Please do continue to try to find more bugs on your own. Jiayous :) 

---

If I may, I have some suggestions for the UI.

### Readability of help message

I would recommend that for the printed list if available when "help" command, have each command be on its own line. So instead of
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/88828097/53f0efbe-bd7c-4c51-8cbf-50ce3bac3966)
have it like
```
bye -> exit chatbot
list -> show tasks
todo [descr] -> adds todo task
deadline [descr]/by [date] -> adds deadline task
event [descr]/from [date] /to [date] -> add event tasks
...
```
(Ps. there seems to be missing (or at least not visible) command(s) such as delete)

### Expand IU to match window size

Currently, if the user enlarges the window (both vertically and horizontally) manually, the UI does not expand to fill the excess space, resulting the application looking ugly.

![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/88828097/2e15f75f-93c6-4f52-ac92-61b965dcb0f4)

**Comment by tayziyi** [comment] 2024-02-29 02:12
Thank you friends for your kind inputs :) 
Will enhance my ip based on these feedback!

**Comment by francisyzy** [comment] 2024-03-02 04:04
Hello, senior from a previous batch here, testing on Kali

Saw that you have fixed the bugs mentioned by [lhy-hoyin](https://github.com/lhy-hoyin)! 

<img width="788" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/24467184/b35d9fdf-9623-4f54-93ba-3fb24e51c678">

However, I think the window resize bug is still there :(

<img width="357" alt="image" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/24467184/785ccdc3-aaf3-4c37-82ba-5cd379c65401">

**Comment by lhy-hoyin** [comment] 2024-03-10 13:52
Hi @tayziyi , I'm not too sure on the timeline, but is the smoke testing period over? If your submissions have been made, perhaps you want to close this issue?

**Closed as completed** 2024-03-12 04:09 UTC
Labels: suitableForPeerHelp, type-HelpRequest :sos:
