### ISSUE TITLE
Level-7 file loading works fine in terminal but "No Such Directory" when using runtest.sh

### ISSUE THREAD

**Issue by belligerentbeagle** [nus-cs2103-AY2324S2/forum#143] opened 2024-01-31 12:03 UTC
System: Mac, Apple Silicon, IntelliJ IDE

As in the title, running my code with the "Play" button in IntelliJ works. My local duke.txt works fine but when I try to run runtest.sh, it reports "java.io.FileNotFoundException: ./src/main/java/data/duke.txt (No such file or directory)"

I get that we have to use relative path, so what am I doing wrong here?

Screenshot from ACTUAL.TXT, I made it print the error message to see what's wrong
<img width="810" alt="Screenshot 2024-01-31 at 7 57 15 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/22781279/7fb662ce-5898-401e-948b-88959dd8ccc1">

Code snippet:
```
    private static void openStoredFile() throws Exception {

        //See if file already exists then parse it
        String filePath = "./src/main/java/data/duke.txt";
        File file = new File(filePath);

        try {
            if (!file.exists()) { //Create if don't exist
                createFile(file);
            } else { //file does exist
               if (isCorrupt(file)) {
                   //file corrupt
                   System.out.println("File Corrupt! Creating new file");
                   createFile(file);
               } else {
                   //parse current info and return.
                   parseTodoFile(file);
               }
            }
        } catch (Exception e) {
            System.out.println("Oh no!");
            System.out.println(e.getMessage());
        }


    }
```

**Comment by belligerentbeagle** [comment] 2024-01-31 12:03
<img width="410" alt="Screenshot 2024-01-31 at 8 03 47 PM" src="https://github.com/nus-cs2103-AY2324S2/forum/assets/22781279/421da537-017b-4943-918b-d2a32913dea0">

If it helps, this is my folder structure

**Comment by Jerome-j** [comment] 2024-01-31 12:05
Hello @belligerentbeagle I suspect it is something to do with the folder hierarchy cos the test files are nested one level deeper. Maybe you can try to specify your directory like this `file.txt`

**Comment by limcaaarl** [comment] 2024-01-31 12:57
Hi, I think this is a duplicate of this [issue](https://github.com/nus-cs2103-AY2324S2/forum/issues/134).

I had the same issue and I followed the solution provided by @bachletuankhai to resolve it.

**Comment by belligerentbeagle** [comment] 2024-01-31 16:51
Thank you for you responses @Jerome-j and @lokidoki102. However, in line with what prof mentioned about how the user might not have a "project root" when you send the project to them, since the relative file path (now ./data/duke.txt) lies in Duke.java and is not a user input, how then would I be able to get my runtest.bat to use ../src/main/java/data/duke.txt instead?

**Comment by belligerentbeagle** [comment] 2024-01-31 16:53
Besides, the current thread linked #134 seems to be dealing with not being able to create the file because the directory was not yet created. I have a different problem where the runtest.bat path to duke.txt is different from that of duke.java to duke.txt but I have to use the same file path string.

**Comment by bachletuankhai** [comment] 2024-01-31 17:05
> Thank you for you responses @Jerome-j and @lokidoki102. However, in line with what prof mentioned about how the user might not have a "project root" when you send the project to them, since the relative file path (now ./data/duke.txt) lies in Duke.java and is not a user input, how then would I be able to get my runtest.bat to use ../src/main/java/data/duke.txt instead?

Well, I think you can modify the test script to copy ../src/main/java/data/duke.txt to something like ./data/duke.txt before running the class.

**Comment by timothysashimi** [comment] 2024-02-01 04:33
you do not need to include src/main/java, the path just needs to start from the earliest branch point in the directory

**Comment by belligerentbeagle** [comment] 2024-02-01 13:07
The problem is that I do not know where the test script sets the current directory to be, and also unsure if my implementation is incorrect, resulting in the test script failing but running it manually is fine.

I further suspect my flawed implementation because it doesn't seem like many have this issue.

For now, I temporarily created a folder called "data" and duplicated duke.txt inside of the test folder.

**Comment by ghost** [comment] 2024-02-01 14:55
Hi, I'm Li Yuan from AY23/24 S1, dropping in to help with the issue

Executing the sh file is relative to where the active directory of the terminal is. As the sh file compiles the program without any issues, this means that the active directory of the terminal is where it should be

On the other hand, executing the Java class is relative to where the Java class is related. Assuming you have not changed the sh file, this should mean that the Java class is compiled and located in `<project root>/bin`. The compiled binaries will not follow the same folder structure as the project's folder structure (it'll be clear if you open up that bin folder), and therefore does not have the relative file path `./src/...` available to it. In fact the way to solve it is to use a relative file path that is not reliant on the project structure

I think this is the case for your issue, do let me know if this explanation helps

**Comment by lhy-hoyin** [comment] 2024-02-01 15:21
@belligerentbeagle  Perhaps you can provide another screenshot of your full folder structure, including the location of your `runtest.bat`?
Alternatively, you can push the latest code to you fork (or a branch of it) and give the link here.

**Comment by neyapraveen** [comment] 2024-02-01 16:53
Hi @belligerentbeagle , I'm from your senior batch, just dropping by to see if I can help. I think it might be useful to look once again at your runtest.sh file as mentioned in a reply above. Assuming it is similar to what I had, the problem might be due to the fact that your runtest.sh script compiles the java code into the `../bin` directory, which is separate from the project's source directory structure. Therefore, using a relative path like `./src/main/java/data/duke.txt` might not work since the classes that are compiled are not structured the same way as your source files. Now, when your Java program is running, the current working directory may not be the same as the directory where your source files are located (../src/main/java/). It could be the directory where the script is executed (../bin/ in your case). When running your Java program from a different directory, it's essential to use a relative path that is relative to the current working directory and not dependent on the project's source structure. Moreover, if you are confused about the current directory in test.sh, you could perhaps try printing out the current working directory in test.sh for debugging purposes, hopefully it helps!

**Comment by hansstanley** [comment] 2024-02-02 06:04
Hi @belligerentbeagle, I'm another senior dropping in to see if I can help.

Others have mentioned using a path relative to the test script outside of the project directory, this is recommended as once the project is compiled into a JAR, the files inside are read-only and shouldn't be used to store the task list. Instead, `data/duke.txt` would be created outside of the JAR during runtime (perhaps [your coursemate's implementation](https://github.com/tituschewxj/ip/blob/master/src/main/java/chatbot/storage/LocalStorage.java) could be used as a reference). Note that when running `Main.java` from your IDE, `data/duke.txt` would be created in your project's `src/main/java` as a result. This can be gitignored as others have done.

Do let me know if you need more clarification.

**Closed as completed** 2024-02-18 08:09 UTC
Labels: type-HelpRequest :sos:
