### ISSUE TITLE
Unable to run ab3 on m2 pro macbook

### ISSUE THREAD

**Issue by RunjiaChen** [nus-cs2103-AY2324S2/forum#151] opened 2024-02-01 05:05 UTC
Hi, I am trying to run ab3 on my macbook but seem to be getting alot of errors, has anyone encountered similar errors before?
![image](https://github.com/nus-cs2103-AY2324S2/forum/assets/142142406/bc130531-b0e4-421e-a24c-2ab6ad756f3a)

**Comment by dillontkh** [comment] 2024-02-01 06:49
I got the same error with the java version I had installed initially. Following the steps in the [advisory for Mac users](https://nus-cs2103-ay2324s2.github.io/website/admin/programmingLanguages.html) fixed it for me.

**Comment by itstrueitstrueitsrealitsreal** [comment] 2024-02-01 15:20
Duplicate of #142, #119

**Closed as completed** 2024-02-18 08:09 UTC
Labels: suitableForPeerHelp, type-HelpRequest :sos:
